### ISSUE TITLE
Restored cache is not functional

### ISSUE THREAD

**Issue by Vampire** [tecolicom/actions-use-homebrew-tools#4]
With
```yaml
- name: 'Install Wine'
  uses: 'tecolicom/actions-use-homebrew-tools@v1'
  with:
    tools: 'wine-stable'
- name: 'Run Wine'
  run: 'wine --version'
```
you can run `wine` after initial run but on repeated run where the cache is restored you get 
```plain
/Users/runner/work/_temp/bac49533-37db-40bd-9e9d-f5f02d6a366a.sh: line 1: wine: command not found
```

**Comment by Vampire** [comment]
I even searched with `find / -type f -name wine` but did not get any result on disk.

**Comment by kaz-utashiro** [comment]
`wine-stable` package install files under `/Applications` and `/Library` directories, but this action archives only `$(brew --prefix)` directory.

I added `path` parameter to specify additional target for the archive.  Also because `/Library` directory requires root privilege to access, related actions was updated to work as root always for archiving and extracting process.

https://github.com/tecolicom/actions-use-homebrew-tools/actions/runs/10413698632

```
- name: 'Install Wine'
  uses: 'tecolicom/actions-use-homebrew-tools@v1.3'
  with:
    tools: 'wine-stable'
    path: /Applications /Library
- name: 'Run Wine'
  run: 'wine --version'
```
