### ISSUE TITLE
Cache fails on extract stage

### ISSUE THREAD

**Issue by jonluca** [tecolicom/actions-use-homebrew-tools#7]
```yaml
      - name: Install correct clang versions to compile xformers
        if: inputs.platform == 'mac'
        #        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm libomp || true
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: "llvm libomp cmake md5sha1sum"
```

This has started failing on cache hits in our pipeline. 

```
  : extract
  archive="/Users/runner/archive-7ab4867c8bc10b4130f04e17e1a47ed3.tz"
  verbose="false"
  ls -l $archive
  if [ -s $archive ]
  then
      opt=-Pxz
      [[ $verbose = yes || $verbose = true ]] && opt+=v
      sudo tar -C / $opt -f $archive
  else
      echo "$archive is empty"
  fi
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_TOKEN: ***
    NODE_ENV: production
    APP_ENV: production
    BUILD_ONNX: true
    APPLE_ID: ***
    APPLE_ID_PASSWORD: ***
    APPLE_APP_SPECIFIC_PASSWORD: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    CSC_LINK: ***
    CSC_KEY_PASSWORD: ***
    SENTRY_AUTH_TOKEN: ***
-rw-r--r--  1 runner  staff  492762299 May  1 22:05 /Users/runner/archive-7ab4867c8bc10b4130f04e17e1a47ed3.tz
usr/local/share/vim/vimfiles/indent: Can't replace existing directory with non-directory
usr/local/share/emacs/site-lisp/cmake: Can't replace existing directory with non-directory
tar: Error exit delayed from previous errors.
```

Might be an easy fix of having tar overwrite the target dir?

![Image](https://github.com/user-attachments/assets/a3671d88-5b67-43fc-b214-48ebb49538c0)
